export * from './lib/foobar1-lib.js';

// --- Generated code to use dependencies ---

import { foobar2Lib } from '@reference-org/foobar2-lib';
import { foobar3Lib } from '@reference-org/foobar3-lib';
import { foobar4Lib } from '@reference-org/foobar4-lib';
import { foobar5Lib } from '@reference-org/foobar5-lib';
import { foobar6Lib } from '@reference-org/foobar6-lib';
import { foobar7Lib } from '@reference-org/foobar7-lib';
import { foobar8Lib } from '@reference-org/foobar8-lib';
import { foobar9Lib } from '@reference-org/foobar9-lib';
import { foobar10Lib } from '@reference-org/foobar10-lib';
import { foobar11Lib } from '@reference-org/foobar11-lib';
import { foobar12Lib } from '@reference-org/foobar12-lib';
import { foobar13Lib } from '@reference-org/foobar13-lib';
import { foobar14Lib } from '@reference-org/foobar14-lib';
import { foobar15Lib } from '@reference-org/foobar15-lib';
import { foobar16Lib } from '@reference-org/foobar16-lib';
import { foobar17Lib } from '@reference-org/foobar17-lib';
import { foobar18Lib } from '@reference-org/foobar18-lib';
import { foobar19Lib } from '@reference-org/foobar19-lib';
import { foobar20Lib } from '@reference-org/foobar20-lib';
import { foobar21Lib } from '@reference-org/foobar21-lib';
import { foobar22Lib } from '@reference-org/foobar22-lib';
import { foobar23Lib } from '@reference-org/foobar23-lib';
import { foobar24Lib } from '@reference-org/foobar24-lib';
import { foobar25Lib } from '@reference-org/foobar25-lib';
import { foobar26Lib } from '@reference-org/foobar26-lib';
import { foobar27Lib } from '@reference-org/foobar27-lib';
import { foobar28Lib } from '@reference-org/foobar28-lib';
import { foobar29Lib } from '@reference-org/foobar29-lib';
import { foobar30Lib } from '@reference-org/foobar30-lib';
import { foobar31Lib } from '@reference-org/foobar31-lib';
import { foobar32Lib } from '@reference-org/foobar32-lib';
import { foobar33Lib } from '@reference-org/foobar33-lib';
import { foobar34Lib } from '@reference-org/foobar34-lib';
import { foobar35Lib } from '@reference-org/foobar35-lib';
import { foobar36Lib } from '@reference-org/foobar36-lib';
import { foobar37Lib } from '@reference-org/foobar37-lib';
import { foobar38Lib } from '@reference-org/foobar38-lib';
import { foobar39Lib } from '@reference-org/foobar39-lib';
import { foobar40Lib } from '@reference-org/foobar40-lib';
import { foobar41Lib } from '@reference-org/foobar41-lib';
import { foobar42Lib } from '@reference-org/foobar42-lib';
import { foobar43Lib } from '@reference-org/foobar43-lib';
import { foobar44Lib } from '@reference-org/foobar44-lib';
import { foobar45Lib } from '@reference-org/foobar45-lib';
import { foobar46Lib } from '@reference-org/foobar46-lib';
import { foobar47Lib } from '@reference-org/foobar47-lib';
import { foobar48Lib } from '@reference-org/foobar48-lib';
import { foobar49Lib } from '@reference-org/foobar49-lib';
import { foobar50Lib } from '@reference-org/foobar50-lib';

export function useDependencies() {
  console.log(foobar2Lib());
  console.log(foobar3Lib());
  console.log(foobar4Lib());
  console.log(foobar5Lib());
  console.log(foobar6Lib());
  console.log(foobar7Lib());
  console.log(foobar8Lib());
  console.log(foobar9Lib());
  console.log(foobar10Lib());
  console.log(foobar11Lib());
  console.log(foobar12Lib());
  console.log(foobar13Lib());
  console.log(foobar14Lib());
  console.log(foobar15Lib());
  console.log(foobar16Lib());
  console.log(foobar17Lib());
  console.log(foobar18Lib());
  console.log(foobar19Lib());
  console.log(foobar20Lib());
  console.log(foobar21Lib());
  console.log(foobar22Lib());
  console.log(foobar23Lib());
  console.log(foobar24Lib());
  console.log(foobar25Lib());
  console.log(foobar26Lib());
  console.log(foobar27Lib());
  console.log(foobar28Lib());
  console.log(foobar29Lib());
  console.log(foobar30Lib());
  console.log(foobar31Lib());
  console.log(foobar32Lib());
  console.log(foobar33Lib());
  console.log(foobar34Lib());
  console.log(foobar35Lib());
  console.log(foobar36Lib());
  console.log(foobar37Lib());
  console.log(foobar38Lib());
  console.log(foobar39Lib());
  console.log(foobar40Lib());
  console.log(foobar41Lib());
  console.log(foobar42Lib());
  console.log(foobar43Lib());
  console.log(foobar44Lib());
  console.log(foobar45Lib());
  console.log(foobar46Lib());
  console.log(foobar47Lib());
  console.log(foobar48Lib());
  console.log(foobar49Lib());
  console.log(foobar50Lib());
}
// --- End generated code ---
